obj-y += drivers/
obj-y += main.o

obj-y += state_manager.o
obj-y += states.o
obj-y += state_machines/sm_common.o
obj-y += state_machines/sm1.o
obj-y += state_machines/sm2.o
obj-y += state_machines/sm2_tasks.o

obj-y += tests/test_runners.o
obj-y += tests/tests.o
obj-y += tests/test_suite.o
obj-y += tests/tests_minimal.o
obj-y += utils.o

obj-y += log_perf.o
obj-y += profiler.o

